name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test environment'
        required: true
        type: choice
        options:
          - dev
          - staging
jobs:
  test-dev:
    if: ${{ github.event.inputs.environment == 'dev' || github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ENVIRONMENT: dev
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci --force
    - name: Create .env file
      run: echo -e "${{ vars.ENV_DEV }}" > .env.dev
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps --force
    - name: Run Playwright tests
      run: NODE_ENV=dev npx playwright test --project=chromium
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-dev
        path: playwright-report/
        retention-days: 30

  test-staging:
    if: ${{ github.event.inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ENVIRONMENT: staging
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci --force
    - name: Create .env file
      run: echo -e "${{ vars.ENV_STAGING }}" > .env.staging
    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps --force
    - name: Run Playwright tests
      run: NODE_ENV=staging npx playwright test --project=chromium
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-staging
        path: playwright-report/
        retention-days: 30
