name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Test environment'
        required: true
        type: choice
        options:
          - dev
          - staging

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ENVIRONMENT: ${{ github.event.inputs.environment || 'dev' }}  # Default to 'dev' if not set
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci --force

      - name: Create .env file
        run: |
          if [ "${{ env.ENVIRONMENT }}" == "staging" ]; then
            echo -e "${{ vars.ENV_STAGING }}" > .env.staging
          else
            echo -e "${{ vars.ENV_DEV }}" > .env.dev
          fi

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps --force

      - name: Run Playwright tests
        run: NODE_ENV=${{ env.ENVIRONMENT }} npx playwright test --project=chromium

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ env.ENVIRONMENT }}
          path: playwright-report/
          retention-days: 30

  deploy-report:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Playwright report artifact
        uses: actions/download-artifact@v4
        with:
          name: playwright-report-${{ github.event.inputs.environment || 'dev' }}
          path: playwright-report

      - name: Deploy Playwright report to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: playwright-report
          clean: true
